### ISSUE TITLE
Reject method does not work using Chronicle_ 2.0.1 NuGet

### ISSUE THREAD

**Issue by nicolas-petrou** [snatch-dev/Chronicle#34]
Running TestApp (repository's test application) with the **Chronicle source code**, the application works fine. If you use **Chronicle_ NuGet** and run TestApp, Reject() does not work as expected.

```
public Task HandleAsync(Message2 message, ISagaContext context)
        {
            Reject();
            Data.IsMessage2 = true;
            Console.WriteLine("M2 reached!");
            CompleteSaga();
            return Task.CompletedTask;
        }
```

**Comment by GooRiOn** [comment]
Had some broken version published somehow. Thx! I've just put 2.0.2 on the NuGet.
