### ISSUE TITLE
need some sample for integration of redis or mongo in test project for custom implementation of ISagaStateRepository

### ISSUE THREAD

**Issue by kkwft** [snatch-dev/Chronicle#45]
need some sample for integration of redis or mongo in test project for custom implementation of ISagaStateRepository

**Comment by UmerIftikhar** [comment]
try implementing this [code](https://github.com/snatch-dev/Chronicle/blob/master/src/Chronicle.Integrations.MongoDB/src/Persistence/MongoSagaStateRepository.cs).  
Should work perfectly fine.
