### ISSUE TITLE
How do get a event on SAGA

### ISSUE THREAD

**Issue by LincolnTx** [snatch-dev/Chronicle#49]
I saw your the DNC-DShop video, and the bus that you use to publish event i guess is RabbitMQ Raw, i want to know if i can use Chronicle library with mediatoR, the current lib for bus i 'm using

**Comment by UmerIftikhar** [comment]
@LincolnTx  You can use mediatoR. See the example below.
However, I am not aware if its gonna have any side effects or not.
**Command**
```
public class CreateOrder: IRequest
{
	public Guid OrderId { get; }

	public CreateOrder(Guid orderId)
	{
		OrderId = orderId;
	}
}
```
**Dispatch Command**
```
var request = new CreateOrder("2045dbef-1520-47e3-bded-b6de59abcfb9");
var result = await _mediator.Send(request);
```

**Saga Handler**
```
public class SampleSagaHandler: IRequestHandler<CreateOrder>
{
	public async Task<Unit> Handle(CreateOrder command, CancellationToken cancellationToken)
	{
		// DO WORK
		return Unit.Value;
	}

}
```

**Comment by LincolnTx** [comment]
Thank you, i will close this issue now
